### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by raphaelniedy** [orgnnice/OrgNNice#1]
Liebes **Org-N-Nice** Team!
Ich würde es sehr begrüßen, wenn ihr eine laufende Dokumentation hättet um euren aktuellen Entwicklungsstand besser beobachten zu können! 

Herzlichen Dank & lg
Raphael

**Comment by markus-hasenberger** [comment]
Lieber Raphael!
Vielen Dank für dein Feedback, wir verwenden Git jedoch nur als Versionierungsprogramm für unseren Code. Den aktuellen Entwicklungsstand kannst du unseren Management Summaries auf unserer Website (www.nice-n.org) entnehmen.

Mit freundlichen Grüßen
orgnnice
